### ISSUE TITLE
cli-plugins not found

### ISSUE THREAD

**Issue by viceice** [AJDurant/choco-docker-engine#10]
By default docker binary distribution brings two cli plugins.
Those are not found, because docker searches `C:\Program Files\docker\cli-plugins\` and this packages installs them to `C:\ProgramData\chocolatey\lib\docker-engine\tools\docker\cli-plugins\`.

So i would suggest to install the docker files to `C:\Program Files\docker` by default.

I think setting the `UnzipLocation `[^1] parameter should do it.

[^1]: https://docs.chocolatey.org/en-us/create/functions/install-chocolateyzippackage#unziplocation-string

**Comment by AJDurant** [comment]
I can run `docker app` and `docker buildx` commands okay with the current install, so I'm not sure how to reproduce this problem.

**Comment by viceice** [comment]
ok, will check again 🤔

**Comment by AJDurant** [comment]
I found it was picking them up from elsewhere on my system. Fixed in d181133.
