### ISSUE TITLE
Fix version string in the chocolateyInstall.ps1

### ISSUE THREAD

**Issue by christianbumann** [AJDurant/choco-docker-engine#13]
The url in the install powershell should not contain a variable but a fix url.
Background. There is an internalization functionality by chocolatey which repacks the package for own package server and e.g. offline szenario. So the url cannot be determined because the variable doesn‘t exists… It may work for install, but not for internalization.

https://docs.chocolatey.org/en-us/features/package-internalizer

Would it possible to fix this and release the newest version? Many thanks

**Comment by AJDurant** [comment]
As in when running the internalizer it can't read the URL because of the variable?

**Comment by AJDurant** [comment]
A workaround would be to set the env var (`$env:ChocolateyPackageVersion`) yourself beforehand. But I will fix this in the next version which I'm updating now.

**Comment by christianbumann** [comment]
Sorry for my late answer. Yes setting the variable works, but then this has to be done for every version…

We have an automated Azure DevOps pipeline which internalizes 4 times a day any package which we already have internalized (with a new version if available) so this automation would not work… 

But many thanks for the fix 👍 so this should now work for me
