### ISSUE TITLE
Cannot find file at '..\\lib\docker-engine\tools\docker\dockerd.exe'

### ISSUE THREAD

**Issue by grochoge** [AJDurant/choco-docker-engine#14]
Trying to run dockerd manually from a command prompt (to temporarily configure proxy settings), I get the following error:

c:\ProgramData\chocolatey\bin\dockerd.exe  
Cannot find file at '..\\lib\docker-engine\tools\docker\dockerd.exe' (c:\ProgramData\chocolatey\lib\docker-engine\tools\docker\dockerd.exe). This usually indicates a missing or moved file.

**Comment by AJDurant** [comment]
Since moving the docker install to Program Files, a shim for dockerd is not created, as it's not expected to be run directly. The upgrade should have cleaned that up.

You can find the actual executable in `$env:ProgramFiles\docker\`, and remove that shim in `c:\ProgramData\chocolatey\bin\`.
