### ISSUE TITLE
Allow configuring the group name

### ISSUE THREAD

**Issue by viceice** [AJDurant/choco-docker-engine#4]
I'm migrating our infrastructure to this package and i already have a docker group.
So i would like to use my existing group.

**Comment by AJDurant** [comment]
If you already have a `daemon.json` config file, then it won't get overwritten, so you can define your own group in there as a workaround. Though being able to configure it would be handy.

**Comment by viceice** [comment]
I know. I'm already doing this, but the group is always created.
